[package]
name = "github-ci-playground"
version = "0.1.0"
authors = ["Ryo Yamashita <qryxip@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
curl-sys = "0.4.21"
openssl-sys = "0.9.49"
