FROM ubuntu:18.04

RUN apt-get update && \
    apt-get install -y libssl-dev pkg-config musl-tools && \
    dpkg -L libssl-dev | grep lib; \
    dpkg -L libssl-dev | grep include || true

ENV CARGO_TARGET_X86_64_UNKNOWN_LINUX_MUSL_LINKER=x86_64-linux-musl-gcc \
    PKG_CONFIG_ALLOW_CROSS=1 \
    OPENSSL_INCLUDE_DIR=/usr/include/x86_64-linux-gnu \
    OPENSSL_LIB_DIR=/usr/lib/x86_64-linux-gnu
