name: CI

on:
  push:
    branches:
      - master
    tags:
      - 'v.*'
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        rust_channel:
          - stable
        rust_target_triple:
          - x86_64-pc-windows-msvc
          - x86_64-pc-windows-gnu
          - x86_64-apple-darwin
          - x86_64-unknown-linux-gnu
          - x86_64-unknown-linux-musl
        include:
          - rust_channel: stable
            rust_target_triple: x86_64-pc-windows-msvc
            rust_host_triple: x86_64-pc-windows-msvc
            os: windows-2019
          - rust_channel: stable
            rust_target_triple: x86_64-pc-windows-gnu
            rust_host_triple: x86_64-unknown-linux-gnu
            os: ubuntu-18.04
          - rust_channel: stable
            rust_target_triple: x86_64-apple-darwin
            rust_host_triple: x86_64-apple-darwin
            os: macOS-10.14
          - rust_channel: stable
            rust_target_triple: x86_64-unknown-linux-gnu
            rust_host_triple: x86_64-unknown-linux-gnu
            os: ubuntu-18.04
          - rust_channel: stable
            rust_target_triple: x86_64-unknown-linux-musl
            rust_host_triple: x86_64-unknown-linux-gnu
            os: ubuntu-18.04

    name: ${{ matrix.rust_channel }}-${{ matrix.rust_target_triple }}
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v1

      - name: apt-get install
        run: |
          sudo apt-get update
          sudo apt-get install -y wine-stable
        if: matrix.os == ubuntu-18.04 && contains(matrix.rust_target_triple, 'pc-windows')

      - name: rustup-init
        run: |
          curl -sSf --tlsv1.2 --proto '=https' -o ./rustup-init https://sh.rustup.rs
          bash ./rustup-init -y --no-modify-path --default-toolchain none
          echo 'export PATH="$HOME/.cargo/bin:$HOME/go/bin:$PATH"' > /tmp/rc.bash
          echo 'export CARGO_CMD=cargo' >> /tmp/rc.bash
          source /tmp/rc.bash
          rustup default ${{ matrix.rust_channel }}-${{ matrix.rust_host_triple }}
          rustup update ${{ matrix.rust_channel }}-${{ matrix.rust_host_triple }}
          rustup component add clippy
          if ${{ matrix.rust_target_triple == matrix.rust_host_triple }}; then
            rustup component add rustfmt
          fi
        shell: bash

      - name: install cross
        run: |
          source /tmp/rc.bash
          CROSS_VERSION=0.1.16
          if ${{ matrix.rust_host_triple == 'x86_64-apple-darwin' }}; then
            curl -sSfL "https://github.com/rust-embedded/cross/releases/download/v$CROSS_VERSION/cross-v$CROSS_VERSION-x86_64-apple-darwin.tar.gz" | tar xz
            mv ./cross ~/.cargo/bin/
          elif ${{ matrix.rust_host_triple == 'x86_64-unknown-linux-gnu' }}; then
            curl -sSfL "https://github.com/rust-embedded/cross/releases/download/v$CROSS_VERSION/cross-v$CROSS_VERSION-x86_64-unknown-linux-musl.tar.gz" | tar xz
            mv ./cross ~/.cargo/bin/
          else
            cargo install --locked --version "$CROSS_VERSION" cross
          fi
          if [ -f ./ci/Dockerfile.${{ matrix.rust_target_triple }} ]; then
            docker build -t ci/${{ matrix.rust_target_triple }} -f ci/Dockerfile.${{ matrix.rust_target_triple }} .
          fi
          echo 'export CARGO_CMD=cross' >> /tmp/rc.bash
          echo "export TARGET_TRIPLE='--target ${{ matrix.rust_target_triple }}'" >> /tmp/rc.bash
        shell: bash
        if: matrix.rust_target_triple != matrix.rust_host_triple

      - name: Display versions
        run: |
          source /tmp/rc.bash
          rustup show
          echo -e '\n'
          rustc -Vv
          echo -e '\n'
          cargo -Vv
          echo -e '\n'
          cargo clippy -V
          echo -e '\n'
          if ${{ matrix.rust_target_triple == matrix.rust_host_triple }}; then
            rustfmt -V
            echo -e '\n'
          else
            cross --version
          fi
          bash --version
        shell: bash

      - name: cargo fmt -- --check
        run: |
          source /tmp/rc.bash
          cargo fmt --all -- --check
        shell: bash
        if: matrix.rust_target_triple == matrix.rust_host_triple

      - name: cargo clippy
        run: |
          source /tmp/rc.bash
          # A hack to avoid IRC
          "$CARGO_CMD" check --all --all-targets --all-features $TARGET_TRIPLE
          if ${{ matrix.os == 'windows-2019' }}; then
            TO_UNIX_PATHS='xargs cygpath -u'
          else
            TO_UNIX_PATHS=cat
          fi
          cargo metadata --format-version 1 |
            jq -r '.workspace_members[] as $members | .packages[] | select(.id == $members) | .targets[].src_path' |
            $TO_UNIX_PATHS |
            xargs touch
          "$CARGO_CMD" clippy --all --all-targets --all-features $TARGET_TRIPLE -- -D warnings
        shell: bash

      - name: cargo build
        run: |
          source /tmp/rc.bash
          "$CARGO_CMD" build --all --bins --examples --all-features $TARGET_TRIPLE
          "$CARGO_CMD" build --all --all-targets --all-features $TARGET_TRIPLE
        shell: bash

      - name: cargo test
        run: |
          source /tmp/rc.bash
          "$CARGO_CMD" test --all --all-targets --all-features $TARGET_TRIPLE
        shell: bash

      - name: Run
        run: |
          source /tmp/rc.bash
          if ${{ contains(matrix.rust_target_triple, 'pc-windows') }}; then
            EXE=.exe
          fi
          if ${{ matrix.rust_target_triple == matrix.rust_host_triple }}; then
            DEBUG_TARGET="./target/debug/${GITHUB_REPOSITORY#*/}$EXE"
          else
            DEBUG_TARGET="./target/${{ matrix.rust_target_triple }}/debug/${GITHUB_REPOSITORY#*/}$EXE"
          fi
          if ${{ matrix.os == ubuntu-18.04 && contains(matrix.rust_target_triple, 'pc-windows') }}; then
            wine "$DEBUG_TARGET"
          else
            "$DEBUG_TARGET"
          fi
        shell: bash

      - name: Upload to GitHub Releases
        run: |
          source /tmp/rc.bash
          if ${{ contains(matrix.rust_target_triple, 'pc-windows') }}; then
            EXE=.exe
          fi
          if ${{ matrix.rust_target_triple == matrix.rust_host_triple }}; then
            RELEASE_TARGET="./target/release/${GITHUB_REPOSITORY#*/}$EXE"
          else
            RELEASE_TARGET="./target/${{ matrix.rust_target_triple }}/release/${GITHUB_REPOSITORY#*/}$EXE"
          fi
          ASSET_STEM="${GITHUB_REPOSITORY#*/}-${GITHUB_REF#refs/tags/}-${{ matrix.rust_host_triple }}"
          go get github.com/tcnksm/ghr
          "$CARGO_CMD" build --release --all-features $TARGET_TRIPLE
          git archive -o "./$ASSET_STEM.tar" --prefix "$ASSET_STEM/" HEAD
          tar -xf "./$ASSET_STEM.tar"
          mv "$RELEASE_TARGET" "./$ASSET_STEM/"
          if ${{ matrix.os == 'windows-2019' }}; then
            ASSET="./$ASSET_STEM.zip"
            7z a "$ASSET" "./$ASSET_STEM"
            zipinfo "$ASSET"
          else
            ASSET="./$ASSET_STEM.tar.gz"
            tar -czvf "$ASSET" "./$ASSET_STEM"
          fi
          ghr "${GITHUB_REF#refs/tags/}" "$ASSET"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        if: startsWith(github.ref, 'refs/tags/')
